### ISSUE TITLE
no support for ISO_LEVEL5_SHIFT

### ISSUE THREAD

**Issue by Drezil** [scottkirkwood/key-mon#78]
Hi there.

I don't know if you are still active on this project.

I wanted to have key-mon for screencasting and i have issues with my keyboard-layout (de_neo - http://neo-layout.org/ ) as this layout has 2 more modifiers (alt-gr acts way different than alt unlocking layer 4 by sending ISO_LEVEL5_SHIFT, caps acts as ISO_LEVEL3_SHIFT and some other stuff is funny as well... )

I hacked together a fork that works for me, but its not ideal - as i hardcoded level3 to caps and level5 to AltGr (which is wrong for basically any other layout): https://github.com/Drezil/key-mon/commit/e72da8b67fd4bbd8570a817947a54ae25f5c0511

I also added missing KEY_DEAD_CIRCUMFLEX to the xlib. Maybe you are interested in a pull as soon as i have polished it up (if you wish)

And i also just added the keys for one theme and not for all shipped..

**Comment by scottkirkwood** [comment]
I've added ISO_LEVEL5_SHIFT and KEY_DEAD_CIRCUMFLEX to xlib.

**Comment by Drezil** [comment]
Thank you! 💜
