### ISSUE TITLE
After succesful first run, key-mon crashes on '/tmp/keymon-xxxxxx.svg' file

### ISSUE THREAD

**Issue by ikbensiep** [scottkirkwood/key-mon#83]
Every time I try to run the program, the console throws an error and continues to display an svg file:

    /usr/lib/python2.7/dist-packages/keymon/key_mon.py:281: GtkWarning: IA__gtk_window_set_default_size: assertion 'width >= -1' failed 
    self.window.set_default_size(int(width), int(height))

    lazy_pixbuf_creator.py [123]: ERROR Unable to read '/tmp/keymon-FYdKiB.svg': `

And proceeds to output the entire svg file to the console:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>`
`<!-- Created with Inkscape (http://www.inkscape.org/) -->`

(etc)

The name of the svg file is randomized everytime, ie:

/tmp/keymon-FYdKiB.svg
/tmp/keymon-YrdNMt.svg

etc.

How do I fix this?

**Comment by mardukbp** [comment]
I think this has been solved in this fork https://github.com/aleb/key-mon/commit/0c2c9ed4f7f76e8a2baeb961251412c03a326f4b

**Comment by ismailsunni** [comment]
Same problem. Any update on this? 

Is that commit @mardukbp released?

Thanks

**Comment by ismailsunni** [comment]
I tried to put scale, e.g. `key-mon --scale 1` or `key-mon --scale 1.5`, it works.

**Comment by ismailsunni** [comment]
I can make it work by adding the scale parameter, e.g. `key-mon --scale 2`

**Comment by mardukbp** [comment]
@ismailsunni What do you mean with released? It has not been merged in this repo. But you can clone that fork and install key-mon from there.

**Comment by ismailsunni** [comment]
Hi, @mardukbp I thought it was part of the main repo.

Anyway, it's solved with passing the `scale` parameter or reset the key-mon

**Comment by eltimbalino** [comment]
> I think this has been solved in this fork [aleb@0c2c9ed](https://github.com/aleb/key-mon/commit/0c2c9ed4f7f76e8a2baeb961251412c03a326f4b)

I don't think this solved the problem, it only tidied up logging the error. I edited the line in my lazy_pixbuf_creator.py file to match the changes in the fork. It is only adding " IOError". This had the effect of the bad behaviour continuing, but the svg text not appearing in the terminal when I ^c key-mon.

The bad behaviour I get is after running: 
`key-mon` --visible_click --scale 2  
The first time I click anywhere, an orange circle expands from my point, and then just remains around my pointer until I kill key-mon. Behaviour is not affected by --scale options.

**Comment by JIGITUP** [comment]
`--visible_click` is so buggy in my case, but the `--scale 1` in my launcher solved this exact issue for me.

MX Linux 19.2 amd64

**Comment by scottkirkwood** [comment]
I believe most of the buginess of highly visible click is fixed now in 1.20
