### ISSUE TITLE
needs code ported to Python3

### ISSUE THREAD

**Issue by androclus** [scottkirkwood/key-mon#85]
Python 2 is nearing end-of-life; many Linux OS's are abandoning P2-based code, including the several dependencies that key-mon requires (python-xlib, pygtk, python-xml, etc.)

key-mon was/is the best screen key/mouse visualizer out there. For the utility to survive, and to help any/everyone who loves this program and uses it, it BADLY needs to be ported to Python 3.

I do not program in Python, and have a full plate, or I would take the port on as a project.

**Comment by scottkirkwood** [comment]
I'm looking, there are some support libraries like I need to change as
well, could be a while.

**Comment by mclegrand** [comment]
I tried to fix this in #87 , which may need some testing and update to documentation & packaging

**Comment by ahangarha** [comment]
I just tested on 11a4d19 commit and everything seems working except one thing:
 - There is clicking issue if the option "highly visible click" be active.
 - If some keys like space or tab be pressed, some gap is added between keys and it remains there.

**Comment by ahangarha** [comment]
I have also noticed these warnings if I run key-mon in terminal:

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/keymon/settings.py", line 142, in _combo_changed
    self._update_option(option, val, str_val)
  File "/usr/local/lib/python3.8/dist-packages/keymon/settings.py", line 150, in _update_option
    setattr(self.settings.options, option, str_val)
  File "/usr/local/lib/python3.8/dist-packages/keymon/options.py", line 271, in __setattr__
    self.__dict__['_options'][name].value = value
  File "/usr/local/lib/python3.8/dist-packages/keymon/options.py", line 185, in _set_value
    self._set_attr_value('_value', val)
  File "/usr/local/lib/python3.8/dist-packages/keymon/options.py", line 169, in _set_attr_value
    setattr(self, attr, float(val))
ValueError: could not convert string to float: ''
```

I couldn't figure out in what circumstances it happens!

**Comment by RYNEQ** [comment]
I seems there is some dependency problems. 
I was able to successfully run the latest commit  by installing `PyGObject`, `pycairo` and `python3-xlib` from pip (not the debian repo) in virtualenv and everything seems stable (not fully tested)

**Comment by scottkirkwood** [comment]
It's all working now with Python3 thanks for everyone's help.
