### ISSUE TITLE
Update repo link

### ISSUE THREAD

**Issue by ahangarha** [scottkirkwood/key-mon#91]
Hi

It seems this is the main and latest repo for this amazing project. Yet, everywhere including in the repo itself (INSTALL.rst) and [pypi](https://pypi.org/project/key-mon/), google code repo is introduced as the main repo.

Please update the link.

**Comment by EricCousineau-TRI** [comment]
Seconded. I've mentioned the old-ness on #94, but would love to see the homepage updated!

**Comment by scottkirkwood** [comment]
I believe the instructions are correct now and INSTALL.rst is gone.
